Repository naver/ngrinder, pull requests merged in 2018-08, with the labels that each got.

#317 Provide limited agent management menu for user permission
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
  ngrinder-controller/src/main/java/org/ngrinder/common/util/SpringSecurityUtils.java
  ngrinder-controller/src/main/webapp/WEB-INF/ftl/agent/list.ftl
  ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/navigator.ftl
  ngrinder-controller/src/test/java/org/ngrinder/agent/controller/AgentManagerControllerTest.java
Labels: new feature

#321 Add local variable to agent list for check the admin
  ngrinder-controller/src/main/webapp/WEB-INF/ftl/agent/list.ftl
Labels: bug fix

#328 Fix agent filtering logic
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
Labels: bug fix

#329 Pass working directory to test process to avoid wrong ngrinder home path on symbolic lynk
  ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java
Labels: bug fix

#331 Ignore problematic test class
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/ClusteredAgentManagerServiceTest.java
Labels: deal with later

#330 Provide the way to turn off security mode in agent config.
  ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
  ngrinder-core/src/main/java/org/ngrinder/common/constants/AgentConstants.java
  ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
  ngrinder-core/src/main/resources/agent-properties.map
  ngrinder-core/src/main/resources/agent.conf
Labels: new feature

#332 Make the target host field mandatory only in normal security level
  ngrinder-controller/src/main/java/org/ngrinder/common/constant/WebConstants.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
  ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
Labels: bug fix
