Repository naver/ngrinder, pull requests merged in 2020-06, with the labels that each got.

#531 Make checking too many errors optionally
  ngrinder-controller/src/main/java/org/ngrinder/infra/plugin/PluginManager.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/TooManyErrorCheckPlugin.java
  ngrinder-controller/src/main/java/org/ngrinder/security/NGrinderAuthenticationProvider.java
  ngrinder-controller/src/main/java/org/ngrinder/security/NGrinderUserDetailsService.java
  ngrinder-controller/src/main/resources/messages_cn.properties
  ngrinder-controller/src/main/resources/messages_en.properties
  ngrinder-controller/src/main/resources/messages_kr.properties
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_31.xml
  ngrinder-controller/src/test/java/org/ngrinder/security/NGrinderPluginUserDetailsServiceTest.java
  ngrinder-core/src/main/java/net/grinder/SingleConsole.java
  ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
  ngrinder-core/src/main/java/org/ngrinder/model/Status.java
  ngrinder-core/src/main/java/org/ngrinder/model/StatusCategory.java
  ngrinder-frontend/src/img/ball/yellow.png
  ngrinder-frontend/src/js/components/perftest/detail/Config.vue
  ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
Labels: 3.5.0

#530 Support multi user defined data type
  ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
  ngrinder-core/src/main/java/net/grinder/SingleConsole.java
  ngrinder-frontend/src/js/components/common/mixin/ChartMixin.vue
  ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
  ngrinder-frontend/src/js/components/perftest/report/menu/PerfTest.vue
Labels: 3.5.0

#563 Fix typo
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
  ngrinder-controller/src/test/java/org/ngrinder/perftest/service/PerfTestRunnableTest.java
  ngrinder-core/src/main/java/net/grinder/SingleConsole.java
Labels: 3.5.0

#519 Enhance test re-execution speed
  ngrinder-controller/build.gradle
  ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
  ngrinder-controller/src/main/java/org/ngrinder/common/constant/CacheConstants.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/HazelcastService.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/model/NullSingleConsole.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
  ngrinder-controller/src/main/resources/messages_cn.properties
  ngrinder-controller/src/main/resources/messages_en.properties
  ngrinder-controller/src/main/resources/messages_kr.properties
  ngrinder-controller/src/main/resources/ngrinder-sh/agent/run_agent_internal.bat
  ngrinder-controller/src/main/resources/ngrinder-sh/agent/run_agent_internal.sh
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentServiceTest.java
  ngrinder-core/build.gradle
  ngrinder-core/src/main/java/net/grinder/AgentController.java
  ngrinder-core/src/main/java/net/grinder/SingleConsole.java
  ngrinder-core/src/main/java/net/grinder/console/ConsoleFoundationEx.java
  ngrinder-core/src/main/java/net/grinder/console/communication/AcceptDistFilesDigestListener.java
  ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControl.java
  ngrinder-core/src/main/java/net/grinder/console/distribution/FileDistributionHandlerImplementation.java
  ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
  ngrinder-core/src/main/java/net/grinder/engine/agent/FileStore.java
  ngrinder-core/src/main/java/net/grinder/engine/communication/DistFilesDigestMessage.java
  ngrinder-core/src/main/java/net/grinder/messages/agent/RefreshCacheMessage.java
  ngrinder-core/src/main/java/net/grinder/util/FileUtils.java
  ngrinder-core/src/main/java/net/grinder/util/NetworkUtils.java
  ngrinder-core/src/main/java/org/ngrinder/common/util/StreamUtils.java
  ngrinder-core/src/main/java/org/ngrinder/model/Status.java
  ngrinder-core/src/test/java/net/grinder/AgentControllerTest.java
  ngrinder-core/src/test/java/net/grinder/SingleConsoleTest.java
  ngrinder-core/src/test/resources/long-time-prepare-test.py
  ngrinder-frontend/src/js/components/perftest/list/List.vue
Labels: 3.5.0

#566 Fix profile settings in build script
  build.gradle
Labels: 3.5.0

#557 Implement bi-directional agent
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerApiController.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/model/Connection.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/repository/ConnectionRepository.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/HazelcastService.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/task/ConnectionAgentTask.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/AgentManager.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
  ngrinder-controller/src/main/resources/messages_cn.properties
  ngrinder-controller/src/main/resources/messages_en.properties
  ngrinder-controller/src/main/resources/messages_kr.properties
  ngrinder-controller/src/main/resources/ngrinder_agent_home_template/agent_agent.conf
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_31.xml
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentCountMapTest.java
  ngrinder-core/src/main/java/net/grinder/AgentController.java
  ngrinder-core/src/main/java/net/grinder/AgentControllerServerDaemon.java
  ngrinder-core/src/main/java/net/grinder/communication/Acceptor.java
  ngrinder-core/src/main/java/net/grinder/communication/Connector.java
  ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControlImplementation.java
  ngrinder-core/src/main/java/net/grinder/console/communication/ConnectionAgentCommunicationListener.java
  ngrinder-core/src/main/java/net/grinder/console/communication/ConnectionAgentListener.java
  ngrinder-core/src/main/java/net/grinder/console/communication/ConsoleCommunicationImplementationEx.java
  ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
  ngrinder-core/src/main/java/net/grinder/engine/agent/ConnectionAgentCommunicationProxy.java
  ngrinder-core/src/main/java/net/grinder/engine/common/AgentControllerConnectorFactory.java
  ngrinder-core/src/main/java/net/grinder/engine/communication/ConnectionAgentCommunicationMessage.java
  ngrinder-core/src/main/java/net/grinder/engine/communication/ConnectionAgentMessage.java
  ngrinder-core/src/main/java/net/grinder/util/NetworkUtils.java
  ngrinder-core/src/main/java/org/ngrinder/NGrinderAgentStarter.java
  ngrinder-core/src/main/java/org/ngrinder/common/constants/AgentConstants.java
  ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
  ngrinder-core/src/main/resources/agent-properties.map
  ngrinder-core/src/main/resources/agent.conf
  ngrinder-core/src/test/java/net/grinder/util/NetworkUtilTest.java
  ngrinder-frontend/src/js/components/agent/List.vue
  ngrinder-frontend/src/js/components/agent/modal/AddConnectionAgentModal.vue
  ngrinder-frontend/src/js/components/perftest/detail/Config.vue
  ngrinder-frontend/src/js/components/perftest/modal/HostModal.vue
  ngrinder-frontend/src/js/components/script/Editor.vue
Labels: 3.5.0

#564 Integrate liquibase change logs
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog.xml
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_28.xml
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_29.xml
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_30.xml
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_31.xml
  ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_MYSQL.xml
  ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
  ngrinder-core/src/main/java/org/ngrinder/model/User.java
  tools/migrator/create-tables.sql
Labels: 3.5.0

#571 Prevent zombie agents from remaining in distributed cache
  ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
  ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControlImplementation.java
Labels: 3.5.0, bug fix

#573 Make chart duration show correctly
  ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
  ngrinder-frontend/src/js/components/perftest/report/menu/PerfTest.vue
Labels: 3.5.0

#572 Adjust editor console size
  ngrinder-frontend/src/js/components/script/Editor.vue
Labels: 3.5.0

#570 Feature/adjust custom classpath priority
  .gitignore
  ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
  ngrinder-controller/src/test/java/org/ngrinder/agent/controller/AgentManagerApiControllerTest.java
  ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
Labels: 3.5.0

#574 Add today icon on the perftest created today
  ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
  ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
  ngrinder-frontend/src/img/icon_today.png
  ngrinder-frontend/src/js/components/perftest/list/List.vue
  ngrinder-frontend/src/js/components/perftest/list/mixin/TableConfig.vue
Labels: 3.5.0

#579 Make monitor chart to be draw correctly
  ngrinder-frontend/src/js/components/perftest/report/DetailReport.vue
Labels: 3.5.0, bug fix

#580 Prevent NPE when attach file revision
  ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
Labels: 3.5.0, bug fix

#581 Set default locale to "en" when fail to detect user locale
  ngrinder-frontend/src/js/utils.js
Labels: bug fix

#587 Handle case of no sampling model
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
Labels: 3.5.0, bug fix
