Repository naver/ngrinder, pull requests merged in 2021-04, with the labels that each got.

#787 Change deprecated babel-eslint to new module
  ngrinder-frontend/.eslintrc.js
  ngrinder-frontend/package.json
Labels: 3.5.5

#790 Hide agent download link to general user in agent management page
  ngrinder-frontend/src/js/components/agent/List.vue
Labels: 3.5.5

#788 Fix fail of auto-upgrade from 3.4.x to 3.5.x
  ngrinder-controller/src/main/java/org/ngrinder/infra/init/DatabaseUpdater.java
Labels: 3.5.5, bug fix

#785 Add subregion concept to cluster mode
  build.gradle
  ngrinder-controller/build.gradle
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentDownloadController.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerApiController.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/controller/MonitorDownloadController.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/model/Connection.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/model/PackageDownloadInfo.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentPackageService.java
  ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
  ngrinder-controller/src/main/java/org/ngrinder/common/constant/CacheConstants.java
  ngrinder-controller/src/main/java/org/ngrinder/common/constant/ClusterConstants.java
  ngrinder-controller/src/main/java/org/ngrinder/common/util/RegionUtils.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/HazelcastService.java
  ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/task/RegionInfoTask.java
  ngrinder-controller/src/main/java/org/ngrinder/packages/AgentPackageHandler.java
  ngrinder-controller/src/main/java/org/ngrinder/packages/MonitorPackageHandler.java
  ngrinder-controller/src/main/java/org/ngrinder/packages/PackageHandler.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/repository/PerfTestRepository.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/repository/PerfTestSpecification.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/AgentManager.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ClusteredPerfTestService.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
  ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
  ngrinder-controller/src/main/java/org/ngrinder/region/model/RegionInfo.java
  ngrinder-controller/src/main/java/org/ngrinder/region/service/RegionService.java
  ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java
  ngrinder-controller/src/main/resources/cluster-properties.map
  ngrinder-controller/src/main/resources/messages_cn.properties
  ngrinder-controller/src/main/resources/messages_en.properties
  ngrinder-controller/src/main/resources/messages_kr.properties
  ngrinder-controller/src/main/resources/ngrinder_agent_home_template/agent_agent.conf
  ngrinder-controller/src/test/java/org/ngrinder/agent/controller/AgentManagerApiControllerTest.java
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentCountMapTest.java
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentServiceTest.java
  ngrinder-controller/src/test/java/org/ngrinder/agent/service/MockAgentService.java
  ngrinder-controller/src/test/java/org/ngrinder/perftest/service/PerfTestRunnableTest.java
  ngrinder-controller/src/test/java/org/ngrinder/region/service/RegionServiceTest.java
  ngrinder-core/src/main/java/net/grinder/AgentController.java
  ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControlImplementation.java
  ngrinder-core/src/main/java/net/grinder/console/communication/ConnectionAgentListener.java
  ngrinder-core/src/main/java/net/grinder/engine/communication/ConnectionAgentMessage.java
  ngrinder-core/src/main/java/net/grinder/engine/controller/AgentControllerIdentityImplementation.java
  ngrinder-core/src/main/java/org/ngrinder/NGrinderAgentStarterParam.java
  ngrinder-core/src/main/java/org/ngrinder/common/constants/AgentConstants.java
  ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
  ngrinder-core/src/main/java/org/ngrinder/model/AgentInfo.java
  ngrinder-core/src/main/java/org/ngrinder/service/IAgentManagerService.java
  ngrinder-core/src/main/resources/agent-properties.map
  ngrinder-core/src/main/resources/agent.conf
  ngrinder-frontend/src/js/components/Base.vue
  ngrinder-frontend/src/js/components/agent/List.vue
  ngrinder-frontend/src/js/components/agent/mixin/TableConfig.vue
  ngrinder-frontend/src/js/components/agent/modal/AddConnectionAgentModal.vue
  ngrinder-frontend/src/js/components/common/navigator/UserMenu.vue
  ngrinder-frontend/src/js/components/perftest/detail/Config.vue
  ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
Labels: 3.5.5, more test required

#793 Clean up code NgrinderControllerStarter
  ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java
Labels: 3.5.5

#791 Change to use OSSRH for deployment ngrinder binary to maven central
  build.gradle
  gradle.properties
Labels: 3.5.5

#795 Make AgentService.getLocalAgents() to return only it's own local agents
  ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
  ngrinder-core/src/main/java/org/ngrinder/service/AbstractAgentService.java
  ngrinder-core/src/main/java/org/ngrinder/service/IAgentManagerService.java
Labels: 3.5.5, bug fix

#796 Make footer have fixed height
  ngrinder-frontend/src/js/components/common/Copyright.vue
Labels: 3.5.5

#789 Change perftest script template to use new HTTP client
  ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyScriptHandler.java
  ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyWithLegacyHttpClientScriptHandler.java
  ngrinder-controller/src/main/java/org/ngrinder/script/handler/ScriptHandler.java
  ngrinder-controller/src/main/resources/script_template/basic_template_groovy.ftl
  ngrinder-controller/src/main/resources/script_template/legacy_template_groovy.ftl
  ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequest.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPResponse.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPatch.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPost.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPut.java
Labels: 3.5.5

#794 Provides multipart form data parameter
  ngrinder-controller/src/main/resources/script_template/basic_template_groovy.ftl
  ngrinder-controller/src/main/resources/script_template/legacy_template_groovy.ftl
  ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequest.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequester.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPatch.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPost.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPut.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/BasicMultipartEntity.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/DelegateDataStreamChannel.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/FileMultipartEntity.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntity.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntityBuilder.java
  ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntityProducer.java
Labels: 3.5.5

#798 Clean up build scripts
  build.gradle
  ngrinder-controller/build.gradle
  ngrinder-core/build.gradle
  ngrinder-frontend/build.gradle
  ngrinder-groovy/build.gradle
  ngrinder-runtime/build.gradle
Labels: 3.5.5
